# Generated by Django 4.0.6 on 2022-08-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='Producto')),
                ('price', models.IntegerField(verbose_name='Producto')),
                ('units', models.IntegerField(verbose_name='Cantidad')),
                ('comment', models.TextField(verbose_name='Comentarios')),
                ('purshased', models.BooleanField(default=False, verbose_name='Comprado')),
            ],
        ),
    ]
