# Generated by Django 4.0.6 on 2022-08-26 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compras',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AddField(
            model_name='compras',
            name='purshased_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Compra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compras',
            name='price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
